apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-python
  namespace: kafka
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  # image: spark:3.5.3
  image: spark-pg:1.0.0
  imagePullPolicy: IfNotPresent
  # mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  mainApplicationFile: local:///app/spark.py
  sparkVersion: 3.5.3
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    instances: 1
    cores: 1
    memory: 512m